/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafetyThresholdsRouteImport } from './routes/safety-thresholds'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LanguageGapRouteImport } from './routes/language-gap'
import { Route as HealthcareRiskReportRouteImport } from './routes/healthcare-risk-report'
import { Route as FailuresRouteImport } from './routes/failures'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as IndexRouteImport } from './routes/index'

const SafetyThresholdsRoute = SafetyThresholdsRouteImport.update({
  id: '/safety-thresholds',
  path: '/safety-thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageGapRoute = LanguageGapRouteImport.update({
  id: '/language-gap',
  path: '/language-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRiskReportRoute = HealthcareRiskReportRouteImport.update({
  id: '/healthcare-risk-report',
  path: '/healthcare-risk-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FailuresRoute = FailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/domains': typeof DomainsRoute
  '/failures': typeof FailuresRoute
  '/healthcare-risk-report': typeof HealthcareRiskReportRoute
  '/language-gap': typeof LanguageGapRoute
  '/live': typeof LiveRoute
  '/safety-thresholds': typeof SafetyThresholdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/domains': typeof DomainsRoute
  '/failures': typeof FailuresRoute
  '/healthcare-risk-report': typeof HealthcareRiskReportRoute
  '/language-gap': typeof LanguageGapRoute
  '/live': typeof LiveRoute
  '/safety-thresholds': typeof SafetyThresholdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/domains': typeof DomainsRoute
  '/failures': typeof FailuresRoute
  '/healthcare-risk-report': typeof HealthcareRiskReportRoute
  '/language-gap': typeof LanguageGapRoute
  '/live': typeof LiveRoute
  '/safety-thresholds': typeof SafetyThresholdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmarks'
    | '/domains'
    | '/failures'
    | '/healthcare-risk-report'
    | '/language-gap'
    | '/live'
    | '/safety-thresholds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmarks'
    | '/domains'
    | '/failures'
    | '/healthcare-risk-report'
    | '/language-gap'
    | '/live'
    | '/safety-thresholds'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/domains'
    | '/failures'
    | '/healthcare-risk-report'
    | '/language-gap'
    | '/live'
    | '/safety-thresholds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRoute
  DomainsRoute: typeof DomainsRoute
  FailuresRoute: typeof FailuresRoute
  HealthcareRiskReportRoute: typeof HealthcareRiskReportRoute
  LanguageGapRoute: typeof LanguageGapRoute
  LiveRoute: typeof LiveRoute
  SafetyThresholdsRoute: typeof SafetyThresholdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safety-thresholds': {
      id: '/safety-thresholds'
      path: '/safety-thresholds'
      fullPath: '/safety-thresholds'
      preLoaderRoute: typeof SafetyThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language-gap': {
      id: '/language-gap'
      path: '/language-gap'
      fullPath: '/language-gap'
      preLoaderRoute: typeof LanguageGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare-risk-report': {
      id: '/healthcare-risk-report'
      path: '/healthcare-risk-report'
      fullPath: '/healthcare-risk-report'
      preLoaderRoute: typeof HealthcareRiskReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failures': {
      id: '/failures'
      path: '/failures'
      fullPath: '/failures'
      preLoaderRoute: typeof FailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRoute,
  DomainsRoute: DomainsRoute,
  FailuresRoute: FailuresRoute,
  HealthcareRiskReportRoute: HealthcareRiskReportRoute,
  LanguageGapRoute: LanguageGapRoute,
  LiveRoute: LiveRoute,
  SafetyThresholdsRoute: SafetyThresholdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
